name: server-prod

on:
  push:
    branches: [ "releases/prod" ]
    paths: 
      - 'client/**'
      - 'server/**'
      - 'Dockerfile'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Build docker container image 
    - run: docker build . -t app-bcc-africa-prod-server
    # Stop and remove old docker container (https://stackoverflow.com/questions/34228864/stop-and-delete-docker-container-if-its-running)
    - run: docker stop app-bcc-africa-prod-server || true && docker rm app-bcc-africa-prod-server || true
    # Start new container
    - run: docker run -d -p "8080":"8080" --restart unless-stopped --env-file ~/app-bcc-africa/server/.env.prod --name=app-bcc-africa-prod-server app-bcc-africa-prod-server



